spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/weixinsell?characherEncoding=utf-8&userSSL=false
    username: root
    password: root
  jpa:
    show-sql: true #显示sql
  jackson:
    default-property-inclusion: non_null #jsckson序列化忽略null
server:
  context-path: /sell
  port: 8088

#微信公众号相关配置
wechat:
  mpAppId:
  mpAppSecret:
